name: Deploy Master branch

on:
  push:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      stage: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
